[tool.poetry]
name = "legendkit"
version = "0.2.0"
description = "Legend creation and manipulation with ease for matplotlib"
authors = ["Mr-Milk <yb97643@um.edu.mo>"]
license = "MIT"

[tool.poetry.dependencies]
python = ["^3.7", "^3.8", "^3.9", "^3.10"]
matplotlib = "^3.5"

[tool.poetry.group.dev.dependencies]
Sphinx = "^5.1.1"
sphinx-gallery = "^0.11.1"
furo = "^2022.6.21"
pytest = "^7.1.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
